### ISSUE TITLE
训练环境

### ISSUE THREAD

**Issue by ExitPath** [Rossil2012/rl-air-combat#1]
您好，请问训练环境在哪里可以找到？

**Comment by Rossil2012** [comment]
不好意思，训练环境不能提供。但是你可以根据接口来实现自己的环境。
训练环境在连接建立时接受这样一个C结构体，用于设置初始位姿：
https://github.com/Rossil2012/rl-air-combat/blob/35f78a5a3f90e07096c0cc18ceffa836b5fedff2/utils/define.py#L92-L100
之后每次收到以下控制量后：
https://github.com/Rossil2012/rl-air-combat/blob/35f78a5a3f90e07096c0cc18ceffa836b5fedff2/utils/define.py#L74-L80
计算得到下一时刻位姿后返回：
https://github.com/Rossil2012/rl-air-combat/blob/35f78a5a3f90e07096c0cc18ceffa836b5fedff2/utils/define.py#L83-L89
也就是说，你需要实现一个TCP服务器，和一个战机动力学模型。最好是C/C++，因为代码为了简化，直接使用了C/C++结构体的内存布局用于（反）序列化的。而如果出于希望修改序列化方式，或者动力学模型的输入输出不同等原因你想修改代码，可以阅读env/combat_env.py以及env/socket_env.py。

**Comment by ExitPath** [comment]
非常感谢您的交流回复，我先研究一下。
